---
output:
  pdf_document: default
  html_document: default
---
# Introduction

# Literature Review

# Data

```{r readingData, echo=FALSE, warning=FALSE, message=FALSE}
# read in the data - add the dataset's path to filePath
library(readxl)
dataset <- read_excel("data/Data.xlsx", sheet = "data1")
incomeData <- read_excel("data/Data.xlsx", sheet = "real") #importing real income
source("code/data_clean.R")
log_data <- data_clean(dataset)
source("code/interpolate.R") #interpolate real income to monthly intervals and clean and log income data
monthly_income <- interpolate(incomeData)
vecm_data <- log_data %>% mutate(monthly_income$log_REAL, .before=log_YR)
colnames(vecm_data)[12] = "log_REAL"
```

```{r graphs, echo=FALSE, warning=FALSE, message=FALSE, fig.align="center", out.width="100%"}
source("code/time_series_plots.R")
time_series_plots(log_data)
```

# Methodology \label{sec:methodology}


## Stationarity \label{sec:stationarity}
```{r stationarityResults, comment=NA, echo=FALSE, warning=FALSE, message=FALSE}
source("code/time_series_data.R")
dset <- time_series_data(vecm_data)

source("code/adf_test.R")
dickeyFuller <- adf_test(dset)
library(broom)

Qadftest <- broom::tidy(dickeyFuller[[1]])
Padftest <- broom::tidy(dickeyFuller[[2]])
Yadftest <- broom::tidy(dickeyFuller[[3]])

dickeyTest <- as.data.frame(bind_rows(Qadftest, Padftest, Yadftest))
rownames(dickeyTest) = c("Quantity legal cigarettes", "Price ratio", "Disposable income")

library(huxtable)

ht <- hux(dickeyTest
      ) %>% huxtable::add_rownames()

bold(ht)[1,]           <- TRUE
bottom_border(ht)[1,]  <- 0.4
align(ht)[,2]          <- "right"
right_padding(ht)      <- 2
left_padding(ht)       <- 2
width(ht)              <- 1
number_format(ht)      <- 2

ht
```


## Cointegration \label{sec:cointegration}

## VECM \label{sec:vecm}

```{r VecmResults, comment=NA, echo=FALSE, warning=FALSE, message=FALSE}
source("code/time_series_data.R")
dset <- time_series_data(vecm_data)

source("code/vecm_tsDyn.R")
vecm2 <- VECM_tsDyn(dset)
source("code/tidy_vecm_results.R")
tidy_vecm <- tidy_vecm_results(vecm2)
vecm_shortrun <- tidy_vecm[[1]]
vecm_longrun <- tidy_vecm[[2]]

library(huxtable)

ht <- hux(vecm_longrun
      ) %>% huxtable::add_rownames()

bold(ht)[1,]           <- TRUE
bottom_border(ht)[1,]  <- 0.4
align(ht)[,2]          <- "right"
right_padding(ht)      <- 2
left_padding(ht)       <- 2
width(ht)              <- 1
number_format(ht)      <- 2

ht

ht <- hux(vecm_shortrun
      ) %>% huxtable::add_rownames()

bold(ht)[1,]           <- TRUE
bottom_border(ht)[1,]  <- 0.4
align(ht)[,2]          <- "right"
right_padding(ht)      <- 2
left_padding(ht)       <- 2
width(ht)              <- 1
number_format(ht)      <- 2

ht
```

## Residual Testing

# Analysis

# Conclusion \label{sec:conclusion}


<!-- capital C fro referencing and then check  -->
<!-- \Cref{theoriginallabel} for tables, sections, tables and writes out e.g. "Table 1" - note capital "C" in \Cref-->

```{r}
# e.g.: source("images/su_logo.jpg") # if you want to source something - quick shortcut is ctrl space and that brings up a list of files also predictive text
```



