---
output: 
  pdf_document:
    # latex_engine: "xelatex"
    citation_package: natbib
    template: template.tex
    toc: true
    toc_depth: 3
    number_sections: true
    keep_tex: false
    fig_caption: true
bibliography: mybib.bib
# indent: false
# documentclass: memoir
documentclass: memoir
# lang: afrikaans, english
lang: english
fontsize: 12pt
# papersize: a4
papersize: letter
classoption: oneside, openany
# geometry: margin=1.5in
margin-ratio: goldenblock
title: An Econometric Analysis of the Illicit South African Tobacco Market
subtitle: An econometric analysis
titel: "Hierdie is die titel van my tesis"
author: "Cassandra Pengelly"
logo: "./images/su_logo.jpg"
author-short: C.\ Pengelly
degree-short: MCom (Economics)
degree: Master in Economics
graad-short: MCom (Ekonomie)
graad: Magister in Ekonomie
#address: yes # comment out to remove address in abstract
faculty: Faculty of Economic and Management Sciences
fakulteit: Fakulteit Ekonomiese en Bestuurswetenskappe
supervisor: Prof.\ W.\ H. Boshoff
year: 2023
month: 8
abstract: abstract.Rmd
#acknowledgements: acknowledgements.Rmd
lot: true
lof: true
# nomenclature: nomenclature.Rmd
# loa: loa.Rmd
header-includes:
- \usepackage{subfig}
- \setlength\parindent{0pt}\setlength{\parskip}{6pt plus 6pt minus 1pt}
# - \usepackage{float}
# - \usepackage{floatrow}
# - \floatsetup[figure]{capposition=top}
# - \floatsetup[table]{capposition=top} 
# - \usepackage{caption}
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, include= FALSE}
rm(list = ls())
gc()
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo=FALSE,
                      fig.width = 6, fig.height = 3, fig.align = 'center',
                      fig.ext = 'png', dev = 'png', dpi = 600) 
# adjust dpi for image quality/knit speed
library(pacman)
pacman::p_load(tidyverse, glue, huxtable, gridExtra, wesanderson, ggrepel, tsDyn, dplyr, zoo, dplyr, broom, seasonal, deseasonalize, ggplot, ggplot2, texreg) 
# can load all packages here - don't need to include them separately in the other scripts and RMD files 
```

```{r child = 'body.Rmd'}
```

\appendix
\appendixpage

```{r child = 'appendix.Rmd'}
```

\clearpage